// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgsvs3h4YQJ50xZ2_1huEpqXB730J6eAA',
    appId: '1:261256318976:web:9974b4b840603dda8208e5',
    messagingSenderId: '261256318976',
    projectId: 'fir-example-da20e',
    authDomain: 'fir-example-da20e.firebaseapp.com',
    storageBucket: 'fir-example-da20e.firebasestorage.app',
    measurementId: 'G-V3T2KSHJQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiyXbD-Laq56PZIDsDDSRnbcOmLNJ0oKc',
    appId: '1:261256318976:android:6d72ae8f2c31e9c18208e5',
    messagingSenderId: '261256318976',
    projectId: 'fir-example-da20e',
    storageBucket: 'fir-example-da20e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCs5VHbZbAg2FXO-FPqo_IpO7X-xwwzik',
    appId: '1:261256318976:ios:62f4a69fe5629b808208e5',
    messagingSenderId: '261256318976',
    projectId: 'fir-example-da20e',
    storageBucket: 'fir-example-da20e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCs5VHbZbAg2FXO-FPqo_IpO7X-xwwzik',
    appId: '1:261256318976:ios:62f4a69fe5629b808208e5',
    messagingSenderId: '261256318976',
    projectId: 'fir-example-da20e',
    storageBucket: 'fir-example-da20e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgsvs3h4YQJ50xZ2_1huEpqXB730J6eAA',
    appId: '1:261256318976:web:1d97ee2dc1d6a17c8208e5',
    messagingSenderId: '261256318976',
    projectId: 'fir-example-da20e',
    authDomain: 'fir-example-da20e.firebaseapp.com',
    storageBucket: 'fir-example-da20e.firebasestorage.app',
    measurementId: 'G-V5QDEQQRQ0',
  );
}
